# Generated by Django 5.1.4 on 2025-03-16 18:21

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0122_charfield_null_choices'),
        ('os_config_management', '0002_remove_osconfig_config_sets_remove_osconfig_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='config_items',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='not_overridable',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='values',
        ),
        migrations.AddField(
            model_name='configurationinclusion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationinclusion',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='configurationinclusion',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationinclusion',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.CreateModel(
            name='ConfigItemAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('value', models.JSONField(blank=True, null=True)),
                ('not_overridable', models.BooleanField(default=False)),
                ('config_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_config_management.configitem')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_config_management.configuration')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'unique_together': {('configuration', 'config_item')},
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='config_values',
            field=models.ManyToManyField(blank=True, related_name='configurations', through='os_config_management.ConfigItemAssignment', to='os_config_management.configitem'),
        ),
    ]